version: '3.9'

services:
  app:
    container_name: nsp-website-dev
    image: nsp-website-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
